export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};

// export default {
//   login: "Duocnguyeng3",
// id: 78523829,
// node_id: "MDQ6VXNlcjc4NTIzODI5",
// avatar_url: "https://avatars.githubusercontent.com/u/78523829?v=4",
// gravatar_id: "",
// url: "https://api.github.com/users/Duocnguyeng3",
// html_url: "https://github.com/Duocnguyeng3",
// followers_url: "https://api.github.com/users/Duocnguyeng3/followers",
// following_url: "https://api.github.com/users/Duocnguyeng3/following{/other_user}",
// gists_url: "https://api.github.com/users/Duocnguyeng3/gists{/gist_id}",
// starred_url: "https://api.github.com/users/Duocnguyeng3/starred{/owner}{/repo}",
// subscriptions_url: "https://api.github.com/users/Duocnguyeng3/subscriptions",
// organizations_url: "https://api.github.com/users/Duocnguyeng3/orgs",
// repos_url: "https://api.github.com/users/Duocnguyeng3/repos",
// events_url: "https://api.github.com/users/Duocnguyeng3/events{/privacy}",
// received_events_url: "https://api.github.com/users/Duocnguyeng3/received_events",
// type: "User",
// site_admin: false,
// name: null,
// company: null,
// blog: "",
// location: null,
// email: null,
// hireable: null,
// bio: null,
// twitter_username: null,
// public_repos: 6,
// public_gists: 0,
// followers: 0,
// following: 0,
// created_at: "2021-02-04T04:58:15Z",
// updated_at: "2021-05-03T14:23:51Z"
// }
